apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
    - name: myapp
      image: ttl.sh/abhinavsiddharth007:2h
      ports:
        - containerPort: 4444
      livenessProbe:
        httpGet:
          path: /
          port: 4444
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /
          port: 4444
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 3
